AWSTemplateFormatVersion: 2010-09-09
Description: "Template to create a static web site with cloudfront backed by S3"
Metadata:
  myDistribution:
    Description: "A cloudfront distribution"
  S3Bucket:
    Description: "An S3 bucket to host static content"
Parameters:
  xspaceBucketName:
    Type: String
    Default: simple-website-demo
    Description: s3 bucket name
  cloudfrontOriginName:
    Type: String
    Default: simple-website-demo.s3.ca-central-1.amazonaws.com
    Description: s3 bucket name
Resources:
  myDistribution:
    Type: 'AWS::CloudFront::Distribution'
    DependsOn: S3Bucket
    Properties:
      DistributionConfig:
        Origins:
        - DomainName: !Ref cloudfrontOriginName
          Id: myS3Origin
          S3OriginConfig:
            OriginAccessIdentity: origin-access-identity/cloudfront/E2AXFG5DB8Q4J8
        Enabled: 'true'
        PriceClass: 'PriceClass_All'
        DefaultRootObject: index.html
        DefaultCacheBehavior:
            AllowedMethods:
            - DELETE
            - GET
            - HEAD
            - OPTIONS
            - PATCH
            - POST
            - PUT
            TargetOriginId: myS3Origin
            ForwardedValues:
              QueryString: 'false'
              Cookies:
                Forward: none
            TrustedSigners:
            - 1234567890EX
            - 1234567891EX
            ViewerProtocolPolicy: redirect-to-https
          ViewerCertificate:
            cloudFrontDefaultCertificate: 'true'
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: Private
      BucketName: !Ref xspaceBucketName
  BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    DependsOn: myDistribution
    Properties:
      PolicyDocument:
        Id: MyPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForCloudfront
            Effect: Allow
            Principal: 'arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity E2AXFG5DB8Q4J8'
            Action: 's3:GetObject'
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref xspaceBucketName
                - /*
      Bucket: !Ref S3Bucket
Outputs:
  CloudfrontURL:
    Value: !GetAtt
      - myDistribution
      - DomainName
    Description: URL for website hosted on S3
  CloudfrontSecureURL:
    Value: !Join
      - ''
      - - 'https://'
        - !GetAtt
          - myDistribution
          - DomainName
    Description: Secure URL for cloudfront hosting
