AWSTemplateFormatVersion: 2010-09-09
Parameters:
  xspaceBucketName:
    Type: String
    Default: sdpoueme-demo
    Description: s3 bucket name
  cloudfrontOriginName:
    Type: String
    Default: sdpoueme-demo.s3.amazonaws.com
    Description: s3 bucket name
Resources:
  CodeCommit:
    Type: 'AWS::CodeCommit::Repository'
    Properties:
      RepositoryDescription: !Ref xspaceBucketName
      RepositoryName: !Ref xspaceBucketName
  myDistribution:
    Type: 'AWS::CloudFront::Distribution'
    DependsOn: S3Bucket
    Properties:
      DistributionConfig:
        Origins:
        - DomainName: !Ref cloudfrontOriginName
          Id: myS3Origin
          S3OriginConfig:
            OriginAccessIdentity: origin-access-identity/cloudfront/E238DECVLPT20Y
        Enabled: 'true'
        PriceClass: 'PriceClass_All'
        DefaultRootObject: index.html
        DefaultCacheBehavior:
            AllowedMethods:
            - DELETE
            - GET
            - HEAD
            - OPTIONS
            - PATCH
            - POST
            - PUT
            TargetOriginId: myS3Origin
            ForwardedValues:
              QueryString: 'false'
              Cookies:
                Forward: none
            TrustedSigners:
            - 1234567890EX
            - 1234567891EX
            ViewerProtocolPolicy: allow-all
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: Private
      BucketName: !Ref xspaceBucketName
  BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      PolicyDocument:
        Id: MyPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForCloudfront
            Effect: Allow
            Principal: 'origin-access-identity/cloudfront/E238DECVLPT20Y'
            Action: 's3:GetObject'
            Resource: !Join 
              - ''
              - - 'arn:aws:s3:::'
                - !Ref xspaceBucketName
                - /*
      Bucket: !Ref S3Bucket
Outputs:
  CloudfrontURL:
    Value: !GetAtt
      - myDistribution
      - DomainName
    Description: URL for website hosted on S3
  CloudfrontDistribution:
    Value: !Ref logicalName
    Description: Cloudfront distribution ID
  CloudfrontSecureURL:
    Value: !Join 
      - ''
      - - 'https://'
        - !GetAtt 
          - myDistribution
          - DomainName
    Description: Secure URL for cloudfront hosting
