apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
 
metadata:
  name: calar-eks
  region: us-east-1
 
iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: rds-db-access
      namespace: calar
      labels: {role: "backend"}
    attachPolicyARNs:
    - "arn:aws:iam::aws:policy/AmazonRDSFullAccess"
